services:
  stunnel-service:
    build:
      context: ./stunnel
      dockerfile: Dockerfile
    hostname: stunnel-service
    networks:
      - sslh-network
    ports:
      - 443:8443
    volumes:
      - ./stunnel/stunnel.conf:/etc/stunnel/stunnel.conf

  sslh-service:
    build:
      context: ./sslh
      dockerfile: Dockerfile
      args:
        DAEMON_OPTS: ${DAEMON_OPTS}
    hostname: sslh-service
    networks:
      - sslh-network
    environment:
      - DAEMON_OPTS=${DAEMON_OPTS}
    volumes:
      - ./sslh/sslh.conf:/etc/default/sslh

  dropbear-service:
    build:
      context: ./dropbear
      dockerfile: Dockerfile
      args:
        SSH_PASSWORD: ${SSH_PASSWORD}
        SSHUSER: ${SSHUSER}
    hostname: dropbear-service
    environment:
      - USER_NAME=${USER_NAME}
      - USER_PASSWORD=${USER_PASSWORD}
    networks:
      - sslh-network

  udpgw-service:
    build:
      context: ./udpgw
      dockerfile: Dockerfile
    hostname: udpgw-service
    networks:
      - sslh-network

networks:
  sslh-network:
