services:
  stunnel-service:
    build:
      context: ./stunnel
      dockerfile: Dockerfile
    hostname: stunnel-service
    networks:
      - sslh-network
    ports:
      - 443:8443
    volumes:
      - ./stunnel/stunnel.conf:/etc/stunnel/stunnel.conf
    restart: always

  sslh-service:
    build:
      context: ./sslh
      dockerfile: Dockerfile
      args:
        DAEMON_OPTS: ${DAEMON_OPTS}
    hostname: sslh-service
    networks:
      - sslh-network
    environment:
      - DAEMON_OPTS=${DAEMON_OPTS}
    volumes:
      - ./sslh/entrypoint.sh:/opt/sslh/entrypoint.sh
    restart: always

  dropbear-service:
    build:
      context: ./dropbear
      dockerfile: Dockerfile
      args:
        SSH_PASSWORD: ${SSH_PASSWORD}
        SSHUSER: ${SSHUSER}
    hostname: dropbear-service
    networks:
      - sslh-network
    restart: always

  udpgw-service:
    build:
      context: ./udpgw
      dockerfile: Dockerfile
    hostname: udpgw-service
    networks:
      - sslh-network
    ports:
      - "0.0.0.0:7300:7300"
    volumes:
      - ./udpgw/udpgw.json:/app/udpgw.json
    restart: always

networks:
  sslh-network:
